# This file tells YOLOv8 where to find your dataset & what classes it’s detecting

# Train images
train: /Users/dhananjaytiwari/Desktop/Programming/CODING/PROJECTS/helmet-guard/datasets/helmet_data/images/train
# Validation images
val: /Users/dhananjaytiwari/Desktop/Programming/CODING/PROJECTS/helmet-guard/datasets/helmet_data/images/val

# Number of classes
nc: 3

# Class names
names: ["helmet", "vest", "head"]